name: pilot1
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.5.0=py311haa95532_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h2bbff1b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py311haa95532_0
  - attrs=23.1.0=py311haa95532_0
  - babel=2.11.0=py311haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.2=py311haa95532_0
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.5=hdccc3a2_0
  - boost-cpp=1.78.0=h9f4b32c_4
  - branca=0.7.0=pyhd8ed1ab_1
  - brotli=1.1.0=hcfcfb64_1
  - brotli-bin=1.1.0=hcfcfb64_1
  - brotli-python=1.0.9=py311hd77b12b_7
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.11.17=h56e8100_0
  - cairo=1.16.0=hd694305_1014
  - certifi=2023.11.17=pyhd8ed1ab_0
  - cffi=1.16.0=py311h2bbff1b_0
  - cfitsio=4.2.0=h9ebe7e4_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=win_pyh7428d3b_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - colorama=0.4.6=py311haa95532_0
  - comm=0.1.2=py311haa95532_0
  - contourpy=1.2.0=py311h005e61a_0
  - cryptography=41.0.3=py311h89fc84f_0
  - curl=8.1.2=h68f0423_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.6.7=py311hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.5.0=h63175ca_1
  - fiona=1.9.1=py311ha4db88c_0
  - folium=0.15.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=hbde0cde_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.46.0=py311ha68e1ae_0
  - freetype=2.12.1=hdaf720e_2
  - freexl=1.0.6=h67ca5e6_1
  - gdal=3.6.2=py311h4bd9738_9
  - geopandas=0.14.1=pyhd8ed1ab_0
  - geopandas-base=0.14.1=pyha770c72_0
  - geos=3.11.1=h1537add_0
  - geotiff=1.7.1=hc256dc0_6
  - gettext=0.21.1=h5728263_0
  - glib=2.78.1=h12be248_0
  - glib-tools=2.78.1=h12be248_0
  - gst-plugins-base=1.22.7=h001b923_0
  - gstreamer=1.22.7=hb4038d2_0
  - hdf4=4.2.15=h1b1b6ef_5
  - hdf5=1.12.2=nompi_h57737ce_101
  - icu=70.1=h0e60522_0
  - idna=3.4=py311haa95532_0
  - intel-openmp=2023.2.0=h57928b3_50497
  - ipykernel=6.25.0=py311h746a85d_0
  - ipython=8.15.0=py311haa95532_0
  - ipywidgets=8.0.4=py311haa95532_0
  - jedi=0.18.1=py311haa95532_1
  - jinja2=3.1.2=py311haa95532_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jpeg=9e=h2bbff1b_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.19.2=py311haa95532_0
  - jsonschema-specifications=2023.7.1=py311haa95532_0
  - jupyter=1.0.0=py311haa95532_8
  - jupyter-lsp=2.2.0=py311haa95532_0
  - jupyter_client=8.6.0=py311haa95532_0
  - jupyter_console=6.6.3=py311haa95532_0
  - jupyter_core=5.5.0=py311haa95532_0
  - jupyter_events=0.8.0=py311haa95532_0
  - jupyter_server=2.10.0=py311haa95532_0
  - jupyter_server_terminals=0.4.4=py311haa95532_1
  - jupyterlab=4.0.8=py311haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.25.1=py311haa95532_0
  - jupyterlab_widgets=3.0.9=py311haa95532_0
  - kealib=1.5.0=h61be68b_0
  - kiwisolver=1.4.5=py311h005e61a_1
  - krb5=1.20.1=h5b6d351_0
  - lcms2=2.15=ha5c8aab_0
  - lerc=4.0.0=h63175ca_0
  - libaec=1.1.2=h63175ca_1
  - libblas=3.9.0=20_win64_mkl
  - libbrotlicommon=1.1.0=hcfcfb64_1
  - libbrotlidec=1.1.0=hcfcfb64_1
  - libbrotlienc=1.1.0=hcfcfb64_1
  - libcblas=3.9.0=20_win64_mkl
  - libclang=15.0.7=default_h77d9078_3
  - libclang13=15.0.7=default_h77d9078_3
  - libcurl=8.1.2=h68f0423_0
  - libdeflate=1.17=hcfcfb64_0
  - libexpat=2.5.0=h63175ca_1
  - libffi=3.4.4=hd77b12b_0
  - libgdal=3.6.2=h221c0cb_9
  - libglib=2.78.1=he8f3873_0
  - libhwloc=2.9.1=h51c2c0f_0
  - libiconv=1.17=h8ffe710_0
  - libkml=1.3.0=hd45a9bc_1016
  - liblapack=3.9.0=20_win64_mkl
  - libnetcdf=4.9.1=nompi_hc41bf00_101
  - libogg=1.3.4=h8ffe710_1
  - libpng=1.6.39=h8cc25b3_0
  - libpq=15.3=ha9684e8_0
  - librttopo=1.1.0=he22b5cd_12
  - libsodium=1.0.18=h62dcd97_0
  - libspatialindex=1.9.3=h39d44d4_4
  - libspatialite=5.0.1=hfdcade0_23
  - libsqlite=3.44.2=hcfcfb64_0
  - libssh2=1.11.0=h7dfc565_0
  - libtiff=4.5.0=hf8721a0_2
  - libvorbis=1.3.7=h0e60522_0
  - libwebp-base=1.3.2=hcfcfb64_0
  - libxcb=1.13=hcd874cb_1004
  - libxml2=2.10.4=hc3477c8_0
  - libzip=1.10.1=h1d365fa_3
  - libzlib=1.2.13=hcfcfb64_5
  - lz4-c=1.9.4=h2bbff1b_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mapclassify=2.6.1=pyhd8ed1ab_0
  - markupsafe=2.1.1=py311h2bbff1b_0
  - matplotlib-base=3.8.2=py311h6e989c2_0
  - matplotlib-inline=0.1.6=py311haa95532_0
  - mistune=2.0.4=py311haa95532_0
  - mkl=2023.2.0=h6a75c08_50497
  - msys2-conda-epoch=20160418=1
  - munch=4.0.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclient=0.8.0=py311haa95532_0
  - nbconvert=7.10.0=py311haa95532_0
  - nbformat=5.9.2=py311haa95532_0
  - nest-asyncio=1.5.6=py311haa95532_0
  - networkx=3.2.1=pyhd8ed1ab_0
  - notebook=7.0.6=py311haa95532_0
  - notebook-shim=0.2.3=py311haa95532_0
  - numpy=1.26.2=py311h0b4df5a_0
  - openjpeg=2.5.0=ha2aaf27_2
  - openssl=3.1.4=hcfcfb64_0
  - overrides=7.4.0=py311haa95532_0
  - packaging=23.1=py311haa95532_0
  - pandas=2.1.3=py311hf63dbb6_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.40=h17e33f8_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py311h76d9071_1
  - pip=23.3.1=py311haa95532_0
  - pixman=0.42.2=h63175ca_0
  - platformdirs=3.10.0=py311haa95532_0
  - ply=3.11=py311haa95532_0
  - poppler=23.03.0=h183ae7b_0
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=15.3=hd87cd2b_0
  - proj=9.1.1=heca977f_2
  - prometheus_client=0.14.1=py311haa95532_0
  - prompt-toolkit=3.0.36=py311haa95532_0
  - prompt_toolkit=3.0.36=hd3eb1b0_0
  - psutil=5.9.0=py311h2bbff1b_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py311haa95532_1
  - pyopenssl=23.2.0=py311haa95532_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pyproj=3.5.0=py311h36482e4_0
  - pyqt=5.15.10=py311hd77b12b_0
  - pyqt5-sip=12.13.0=py311h2bbff1b_0
  - pysocks=1.7.1=py311haa95532_0
  - python=3.11.5=he1021f5_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py311haa95532_0
  - python-json-logger=2.0.7=py311haa95532_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - pytz=2023.3.post1=py311haa95532_0
  - pywin32=305=py311h2bbff1b_0
  - pywinpty=2.0.10=py311h5da7b33_0
  - pyyaml=6.0.1=py311h2bbff1b_0
  - pyzmq=25.1.0=py311hd77b12b_0
  - qt-main=5.15.8=h720456b_6
  - qtconsole=5.5.0=py311haa95532_0
  - qtpy=2.4.1=py311haa95532_0
  - referencing=0.30.2=py311haa95532_0
  - requests=2.31.0=py311haa95532_0
  - rfc3339-validator=0.1.4=py311haa95532_0
  - rfc3986-validator=0.1.1=py311haa95532_0
  - rpds-py=0.10.6=py311h062c2fa_0
  - rtree=1.1.0=py311hcacb13a_0
  - scikit-learn=1.3.2=py311h142b183_2
  - scipy=1.11.4=py311h0b4df5a_0
  - send2trash=1.8.2=py311haa95532_0
  - setuptools=68.0.0=py311haa95532_0
  - shapely=2.0.1=py311habfe8a2_0
  - sip=6.7.12=py311hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.10=hfb803bf_0
  - sniffio=1.2.0=py311haa95532_1
  - soupsieve=2.5=py311haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.9.0=h91493d7_0
  - terminado=0.17.1=py311haa95532_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tiledb=2.13.2=h3132609_0
  - tinycss2=1.2.1=py311haa95532_0
  - tk=8.6.12=h2bbff1b_0
  - tornado=6.3.3=py311h2bbff1b_0
  - traitlets=5.7.1=py311haa95532_0
  - typing-extensions=4.7.1=py311haa95532_0
  - typing_extensions=4.7.1=py311haa95532_0
  - tzdata=2023c=h04d1e81_0
  - ucrt=10.0.22621.0=h57928b3_0
  - uriparser=0.9.7=h1537add_1
  - urllib3=1.26.18=py311haa95532_0
  - vc=14.2=h21ff451_1
  - vc14_runtime=14.36.32532=hdcecf7f_17
  - vs2015_runtime=14.36.32532=h05e6639_17
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py311haa95532_1
  - websocket-client=0.58.0=py311haa95532_4
  - wheel=0.41.2=py311haa95532_0
  - widgetsnbextension=4.0.5=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_0
  - winpty=0.4.3=4
  - xerces-c=3.2.4=h63175ca_3
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xyzservices=2023.10.1=pyhd8ed1ab_0
  - xz=5.4.5=h8cc25b3_0
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.4=hd77b12b_0
  - zlib=1.2.13=hcfcfb64_5
  - zstd=1.5.5=hd43e919_0
prefix: C:\Users\Chiara Aquino\anaconda3\envs\pilot1
